=== ADenzie/PRIN143-Activity-03/schema.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://www.example.com"
  xmlns="https://www.example.com"
  elementFormDefault="qualified">

  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lastName" type="xs:string"/>
              <xs:element name="givenName" type="xs:string"/>
              <xs:element name="middleName" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="birthDate" type="xs:date"/>
        <xs:element name="gender">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Male"/>
              <xs:enumeration value="Female"/> 
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="contactDetails">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="emailAddress" type="xs:string"/>
              <xs:element name="mobileNumber">
                <xs:simpleType>
                <xs:restriction base="xs:string">
                <xs:pattern value="[0][9][1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"></xs:pattern>
                </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="address">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="line1" type="xs:string"/>
              <xs:element name="city" type="xs:string"/>
              <xs:element name="province" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="yearLevel">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:enumeration value="1" />
              <xs:enumeration value="2" /> 
              <xs:enumeration value="3" /> 
              <xs:enumeration value="4" /> 
              <xs:enumeration value="5" /> 
              <xs:enumeration value="6" /> 
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="course" type="xs:string"/>
        <xs:element name="campus">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Malolos" />
              <xs:enumeration value="Makati" /> 
              <xs:enumeration value="Mendiola" /> 
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="gwa" type="xs:decimal"/>
        <xs:element name="isEnrolled" type="xs:boolean"/>
        <xs:element name="dateEnrolled" type="xs:dateTime"/>
        <xs:element name="subjects">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="subject" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:positiveInteger" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ADenzie/PRIN143-Activity-03/student.xml
<?xml version="1.0"?>

<student xmlns="https://www.example.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.example.com schema.xsd"
  id="1345">
  <name>
    <lastName>Stark</lastName>
    <givenName>Tony</givenName>
    <middleName></middleName>
  </name>
  <birthDate>1992-10-09</birthDate>
  <gender>Male</gender>
  <contactDetails>
    <emailAddress>tony.stark@email.com</emailAddress>
    <mobileNumber>09171234567</mobileNumber>
  </contactDetails>
  <address>
    <line1>#01 Sample St.</line1>
    <city>City of Malolos</city>
    <province>Bulacan</province>
  </address>
  <yearLevel>2</yearLevel>
  <course>Information Technology</course>
  <campus>Malolos</campus>
  <gwa>1.85</gwa>
  <isEnrolled>true</isEnrolled>
  <dateEnrolled>2025-01-05T09:30:00+08:00</dateEnrolled>
  <subjects>
    <subject>System Integration 1</subject>
    <subject>Networking 2</subject>
    <subject>Programming 2</subject>
  </subjects>
</student>
